### ISSUE TITLE
Version 2.0.3 not in the npm repository

### ISSUE THREAD

**Issue by sgmbr** [apache/cordova-plugin-device#104]
# Bug Report

## Problem
The latest version 2.0.3 is not in the npm repository and therefore `cordova plugin add cordova-plugin-device@2.0.3` fails

### What is expected to happen?
`cordova plugin add cordova-plugin-device@2.0.3` succeeds

### What does actually happen?
`cordova plugin add cordova-plugin-device@2.0.3` fails

## Information

Please publish the latest version to npm.
As far as I know, these other packages are in also the same situation:
- cordova-plugin-inappbrowser
- cordova-plugin-network-information
- cordova-plugin-screen-orientation
- cordova-plugin-splashscreen
- cordova-plugin-statusbar
- cordova-plugin-whitelist

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by erisu** [comment]
The version you are looking for has not been officially release. Please monitor npmjs. Once the plugin appears there, then it is officially available to use.

https://www.npmjs.com/package/cordova-plugin-device

The other packages are in also the same situation.

**Comment by sgmbr** [comment]
Cool, thanks for the clarification :)
