### ISSUE TITLE
device.serial = 'unknown' on ios 12.3.1

### ISSUE THREAD

**Issue by JoshuvaGeorge03** [apache/cordova-plugin-device#105]
# Bug Report
using device.serial on IOS 12.3.1 returns 'unknown'.
### What is expected to happen?

Using device.serial should return the device serial number.

### What does actually happen?
device.serial on IOS 12.3.1 returns 'unknown'.

## Checklist

- [x ] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by timbru31** [comment]
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by magnars** [comment]
Yes, it is reproducible in a new, plain Cordova app. `window.device.serial` gives `"UNKNOWN"`.

**Comment by breautek** [comment]
It is no longer possible to obtain the serial number on both android and ios devices as Apple and Google consider this privilege information. The native APIs to obtain the serial number now only returns `"unknown"`. I forget exactly when iOS made this change.

**Comment by breautek** [comment]
Just for a complete answer... If you're building an internal enterprise app that **will not** be deployed to the app store, you can probably build a plugin (or maybe someone else already has) that queries the MDM service. Apple docs can be found at https://developer.apple.com/business/documentation/MDM-Protocol-Reference.pdf

But doing this for a normal ios app, apple will detect this usage and will not allow the app to be published to the app store.

**Comment by magnars** [comment]
Thanks for taking the time to write a good explanation. 👍
