### ISSUE TITLE
In android 9.0 Device serial is unknown

### ISSUE THREAD

**Issue by smismailalam** [apache/cordova-plugin-device#111]
# Bug Report
In android 9.0 Device serial is unknown
## Problem
when we set target android version="28" or above got the device. serial is "unknown"
### What is expected to happen?
Get device serial in android 9.0

### What does actually happen?
Currently, there have no Properties get devices serial with this permission "android.permission.READ_PHONE_STATE"

## Information
I am adding this permission for device.serial  in androidManifest.xml
<uses-permission android:name="android.permission.READ_PHONE_STATE" />
enable this permission by this plugin
https://www.npmjs.com/package/cordova-plugin-sim
but this plugin has only sim info
how can I get the device.serial with this permission "android.permission.READ_PHONE_STATE"

### Environment, Platform, Device
Cordova experience in android version 9.0

### Version information
android pie (9.0)

**Comment by devWaleed** [comment]
bump

**Comment by timbru31** [comment]
@IsmailAlam786 could you please check if this is related to #91?

**Comment by IsmailAlam786** [comment]
yes but I am facing this issue in all android version 9.0 and above devices

**Comment by IsmailAlam786** [comment]
> @IsmailAlam786 could you please check if this is related to #91?

yes but I am facing this issue in all android version 9.0 and above devices

**Comment by breautek** [comment]
This is probably caused by this change that happened as of android 28 https://developer.android.com/about/versions/pie/android-9.0-changes-28

[READ_PHONE_STATE](https://developer.android.com/reference/android/Manifest.permission.html#READ_PHONE_STATE) permission is now required, then you need to call [getSerial()](https://developer.android.com/reference/android/os/Build.html#getSerial())

**Comment by breautek** [comment]
Also note that declaring the permission in the manifest is not enough. We need to explicitly prompt the user with a permission model now as of android 28. Therefore the current JS api is not going to work very well. We will need a new method that returns a promise.

Therefore perhaps the current `.serial` should be deprecated for android, in favour of a JS `getSerialNumber` method that returns a promise.

**Comment by breautek** [comment]
Actually, I just discovered starting in Android 10, it will be impossible for apps to read serial numbers. See https://developer.android.com/about/versions/10/privacy/changes

**Comment by Legenyes** [comment]
Up ?

**Comment by breautek** [comment]
Unless if you can obtain privilege permissions (e.g. you're working for an phone manufacturer or carrier and able to have apps preinstalled with the privilege permissions granted), reading any non-resettable identifiers is no longer possible.

I've made a PR #143 to add notes reflecting this quirk for android.
