### ISSUE TITLE
IOS: device.uuid returned the same characters on two different iphones

### ISSUE THREAD

**Issue by barakataboujreich** [apache/cordova-plugin-device#114]
Hello,
we use the uuid to allow only 1 device to login to our app, but today we ran into a problem where a user was able to login from a new device without activating it. after analyzing the logs to see how that happened, i was able to notice that the same uuid was generated on two different devices. if someone can enlighten me how is that possible?
old phone: iphone 10
new phone: iPhone 11 Pro, ios: 13.3

now i know that on the same device, if all the apps of the vendor are uninstalled and one of them installed, the uuid will be different. but i can't find any answer for my case. using itunes backup will not change the uuid?

**Comment by roitto** [comment]
https://github.com/apache/cordova-plugin-device#ios-quirk

> The UUID will be the same if app is restored from a backup or iCloud as it is saved in preferences. Users using older versions of this plugin will still receive the same previous UUID generated by another means as it will be retrieved from preferences.

**Comment by breautek** [comment]
I think the comment above sufficiently answers the question.
