### ISSUE TITLE
deviceready not fired with angular 9

### ISSUE THREAD

**Issue by chefchefchef** [apache/cordova-plugin-device#125]
# Bug Report

### What is expected to happen?
when `document.addEventListener("deviceready", onDeviceReady, false);` is registered the success-method (onDeviceReady) should be called.

### What does actually happen?
Sucess method never gets called. Also console-log "deviceready has not fired after 5 seconds." is printed.

## Information
No code changes done with update angular 8 to angular 9. Cordova platform "android" has been removed and added again but without luck.

### Environment, Platform, Device
Samsung Galaxy S7, Android 9
cordova-plugin-device: 2.0.3

**Comment by timbru31** [comment]
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by chefchefchef** [comment]
Somehow after removing platform and multiple plugins and re-add them again it worked fine! Thank you for your time and support!
