### ISSUE TITLE
crashes Ionic 5 app

### ISSUE THREAD

**Issue by liquidcms** [apache/cordova-plugin-device#129]
# Bug Report
as per Ionic docs i have:

import { Device } from '@ionic-native/device/ngx';
constructor(private device: Device) { }
...
console.log('Device UUID is: ' + this.device.uuid);

adding the constructor declaration gives:

 app.component.html:13 ERROR NullInjectorError: StaticInjectorError(AppModule)[Device]: 
  StaticInjectorError(Platform: core)[Device]: 
    NullInjectorError: No provider for Device!

### Environment, Platform, Device

running with:
ionic cordova run browser -l

### Version information
ionic info:
Ionic:

   Ionic CLI                     : 6.11.6 (C:\Program Files\nodejs\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.901.6
   @angular-devkit/schematics    : 9.1.6
   @angular/cli                  : 9.1.6
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.1.0
   @capacitor/core : 2.1.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : 6.0.0, android 8.1.0, browser
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 11 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 1.0.0

System:

   Android SDK Tools : 26.1.1 (C:\android-sdk)
   NodeJS            : v12.18.2 (C:\Program Files\nodejs\node.exe)
   npm               : 6.14.5
   OS                : Windows 7

version of this plugin: @ionic-native/device@5.28.0

## Checklist

- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by breautek** [comment]
This appears to be an issue with ionic, and not with the apache plugin. I think the best place to seek help for this is at https://github.com/ionic-team/ionic-native/issues
