### ISSUE TITLE
this.device.uuid not returning anything unless it's inside post return data

### ISSUE THREAD

**Issue by rr-philips** [apache/cordova-plugin-device#131]
Hello, I'm having some problems when i'm using this plugin. 

For whatever reason, the only time that i can actually get "this.device.uuid" to return anything is inside of a post's promise.then. which is the post call that I need this to work for. I've tried getting it inside of a function, I've tried putting it in an async/await function, I've tried putting it in a function and then calling that function with document.addeventlistener('onready'), the only time that it will return anything is after I need it, and it's been holding me up for about 2 days now...

any thoughts or help on this would be amazing.

`Ionic:

   Ionic CLI                     : 5.4.9 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.803.24
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 9.0.0
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.0, (and 10 other plugins)

Utility:

   cordova-res : 0.9.0 (update available: 0.15.1)
   native-run  : 0.2.9 (update available: 1.2.1)

System:

   ios-deploy : 1.9.2
   ios-sim    : 8.0.2
   NodeJS     : v12.13.0 (/usr/local/bin/node)
   npm        : 6.12.0
   OS         : macOS Catalina
   Xcode      : Xcode 12.0.1 Build version 12A7300
`

`
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-contacts 3.0.1 "Contacts"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-inappbrowser 4.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.0 "cordova-plugin-ionic-webview"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
onesignal-cordova-plugin 2.11.1 "OneSignal Push Notifications"
`

**Comment by timbru31** [comment]
Please show your actual code snippet you use to call the plugin's API.

**Comment by rr-philips** [comment]
`console.log('this is the uuid in ng on init', this.device.uuid);`
or
`post('get_data', {uuid: this.device.uuid, app:'gatss'})`

i'm not trying to do anything crazy with it, just literally call it

**Comment by breautek** [comment]
> then calling that function with document.addeventlistener('onready')

The event you're looking for is `deviceready`. All cordova plugins can only be used after `deviceready` event is fired.

```javascript
document.addEventListener('deviceready', function() {
   // Safe to use cordova plugins here
});
```

See the [docs](https://cordova.apache.org/docs/en/dev/cordova/events/events.html#deviceready) for more details.
