### ISSUE TITLE
NullInjectorError: No provider for Device

### ISSUE THREAD

**Issue by shjdgwj** [apache/cordova-plugin-device#137]
# Bug Report

### What is expected to happen?

There is an error ,NullInjectorError: No provider for Device

### What does actually happen?

It can not be used.

## Information

core.js:4197 ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(Tab1PageModule)[Device -> Device -> Device -> Device -> Device]: 
  NullInjectorError: No provider for Device!
NullInjectorError: R3InjectorError(Tab1PageModule)[Device -> Device -> Device -> Device -> Device]: 
  NullInjectorError: No provider for Device!
    at NullInjector.get (core.js:915)
    at R3Injector.get (core.js:11082)
    at R3Injector.get (core.js:11082)
    at R3Injector.get (core.js:11082)
    at NgModuleRef$1.get (core.js:24199)
    at R3Injector.get (core.js:11082)
    at NgModuleRef$1.get (core.js:24199)
    at R3Injector.get (core.js:11082)
    at NgModuleRef$1.get (core.js:24199)
    at Object.get (core.js:22102)
    at resolvePromise (zone-evergreen.js:798)
    at resolvePromise (zone-evergreen.js:750)
    at zone-evergreen.js:860
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:27425)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at drainMicroTaskQueue (zone-evergreen.js:569)
defaultErrorLogger @ core.js:4197
handleError @ core.js:4245
next @ core.js:27988
schedulerFn @ core.js:24801
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.js:24791
(anonymous) @ core.js:27460
invoke @ zone-evergreen.js:364
run @ zone-evergreen.js:123
runOutsideAngular @ core.js:27364
onHandleError @ core.js:27460
handleError @ zone-evergreen.js:368
runGuarded @ zone-evergreen.js:136
api.microtaskDrainDone @ zone-evergreen.js:670
drainMicroTaskQueue @ zone-evergreen.js:576
Promise.then (async)
scheduleMicroTask @ zone-evergreen.js:552
scheduleTask @ zone-evergreen.js:388
onScheduleTask @ zone-evergreen.js:272
scheduleTask @ zone-evergreen.js:378
scheduleTask @ zone-evergreen.js:210
scheduleMicroTask @ zone-evergreen.js:230
scheduleResolveOrReject @ zone-evergreen.js:847
resolvePromise @ zone-evergreen.js:785
(anonymous) @ zone-evergreen.js:705
webpackJsonpCallback @ bootstrap:25
(anonymous) @ default~detail-detail-module~tab1-tab1-module.js:1

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by timbru31** [comment]
You are using `@ionic-native/device`. You need to seek their, or general Angular support as your error messages indicates. This plugin is only used indirectly by Ionic Native's wrapper.
