### ISSUE TITLE
Why isn't the getSDKVersion() function being used?

### ISSUE THREAD

**Issue by pierremacedo** [apache/cordova-plugin-device#142]
I had to edit the plugin to make it work. It's easier to work with the SDK version than the Android version, so I think this plugin should provide SDK information.

**Comment by breautek** [comment]
My best guess is SDK target is really an android-only concept. All other platforms mainly act on their OS / Browser version to determine capability.

In most cases, SDK details isn't necessary on the webview side either (e.g. a plugin should handle determining SDK version and choosing a specific API to do it's job and that's an implementation detail that the webview shouldn't care about.

Personally I wouldn't be opposed to adding a new android-only property that provides the SDK version. PR is welcome.

**Comment by pierremacedo** [comment]
Thanks for considering reactivating the function. For me, it's important to get the SDK version because the Android version returns something like 5.1.1, while SDK is just 22, for example. I'm building an app where two types of AdMob ads won't work well on SDK 22 to 24. It's easier to deal with it when we know the SDK number. But I was able to edit the plugin and create a device.sdk property.
