### ISSUE TITLE
Is there a way to differentiate between an Android phone and a Huawei phone using this plugin?

### ISSUE THREAD

**Issue by Morgs007** [apache/cordova-plugin-device#148]
Is there a way to differentiate between an Android phone and a Huawei phone using this plugin? 
There is no `platform.is( "huawei" )` ...

Any suggestion?

**Comment by GNozaki** [comment]
I think you could compare `device.manufacturer` to `"Huawei"`, if it is a Huawei phone using Android.

**Comment by jcesarmobile** [comment]
As GNozaki said, you can use device.manufacturer to check the device manufacturer.

But you can't differentiate if the Huawei device is an Android phone or a Harmony phone, not sure if that's what you want. Harmony OS is not officially supported by Apache.
