### ISSUE TITLE
Drop cordova-osx support

### ISSUE THREAD

**Issue by BBosman** [apache/cordova-plugin-device#155]
# Feature Request

## Motivation Behind Feature

With the deprecation of `cordova-osx` as an officially supported platform it seems a logical step to also deprecate its support within this plugin.

## Feature Description

Remove `<platform name="osx">` and related files.

## Alternatives or Workarounds

n/a

## Next steps

If this is a wanted change, I'm willing to create a PR for it.

**Comment by breautek** [comment]
Something like this is generally looked at when we are ready to start preparing a new major release.
