### ISSUE TITLE
app set id

### ISSUE THREAD

**Issue by jacoux** [apache/cordova-plugin-device#159]
# Bug Report

### What is expected to happen?

The device ID should be sent in android using an App set ID. https://developer.android.com/training/articles/app-set-id

### What does actually happen?
This is the new and correct way of sending UID's in android.

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by jcesarmobile** [comment]
I agree, that ID is out of the scope of device plugin.
