### ISSUE TITLE
divece is undefined for ios in 2.1.0 version

### ISSUE THREAD

**Issue by Okkkks** [apache/cordova-plugin-device#170]
# Bug Report

## Problem
device is undefined for ios in 2.1.0 version
### What is expected to happen?
I use check platform in my code

device.platform

and after update from version 2.0.3 to 2.1.0 the cod doesn't work because device is undefined

I was create test project and check it on ios v5.1.1 and for ios v6.2.0 - it's doesn't work for v2.1.0 and works for v2.0.3

see my test project in attachment
[test.zip](https://github.com/apache/cordova-plugin-device/files/8689384/test.zip)

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by jcesarmobile** [comment]
The plugin is in dependencies, but not in the plugins section inside cordova object.
Should look like:
```
"cordova": {
        "plugins": {
            "cordova-plugin-whitelist": {},
            "cordova-plugin-device": {}
        },
        "platforms": [
            "ios"
        ]
    },
```
But it's like
```
"cordova": {
        "plugins": {
            "cordova-plugin-whitelist": {}
        },
        "platforms": [
            "ios"
        ]
    },
```
If you run `cordova plugin add cordova-plugin-device` the plugin will be correctly added and your app will work.
