### ISSUE TITLE
pod version is not the latest version

### ISSUE THREAD

**Issue by zhaoyangyang123** [apache/cordova-plugin-device#187]
# The pod component version is 1.1.3, not the latest version

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by jcesarmobile** [comment]
Thanks for the issue, but we (Apache) don't own the CocoaPods, it was published by "The Adobe PhoneGap Team" according to the CocoaPods page, which, as far as I know, no longer exists.

**Comment by zhaoyangyang123** [comment]
> Thanks for the issue, but we (Apache) don't own the CocoaPods repository for cordova-plugin-device, it was published by "The Adobe PhoneGap Team" according to the CocoaPods page, which, as far as I know, no longer exists.

For iOS, it is more convenient to use CocoaPods integration plug-in. Do you have any plans to do it
