### ISSUE TITLE
device.version returns wrong version on android Q

### ISSUE THREAD

**Issue by julianCast** [apache/cordova-plugin-device#98]
# Bug Report

## Problem
Wront version returned on device running Android Q, Pixel 3.
### What is expected to happen?
device.version on Android Q should return 10 or similar.
### What does actually happen?
device.version on Android Q returns a value considered <= 5.
## Information

Unfortunately I don't own an android Q device, but I get an user reporting that issue, and according to my code the output to .version it's considered a version lower or equal to 5, but I can't tell the value.

Android Q is still on beta so is not a high priority issue, but something to check.

### Command or Code

device.version

### Environment, Platform, Device

Ionic, Android, Pixel 3

### Version information

Ionic CLI  4.12.0
Ionic Framewoek 3.9.2
@ionic/app-scripts 3.1.1

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by janpio** [comment]
Thanks for reporting this @julianCast. We'll try to somehow reproduce this and see what is going on.

**Comment by julianCast** [comment]
Hi! Any news?

**Comment by janpio** [comment]
Did you submit a Pull Request that we missed?

**Comment by julianCast** [comment]
Oh, I don't own a android Q device. I thought by your last message that you'll try to reproduce it, if I can help by any chance I will but I don't have any device with that android version.

**Comment by janpio** [comment]
Same problem for me. You could try it via an Android emulator if you computer can handle it.

**Comment by ndrake** [comment]
On my test Q device (running Beta 4 with cordova-plugin-device 2.0.3), device.version returns '10'.  Remember, device.version is a string, so you'll need to convert it to a number before comparing.

**Comment by julianCast** [comment]
I can't believe I was comparing strings, until now it didnt fail because all the comparations were lower to 10 (android Q). Now, with two digits ( as string), the error is here.
Thank you @ndrake !
