### ISSUE TITLE
Add support for electron platform

### ISSUE THREAD

**Issue by goffioul** [apache/cordova-plugin-device#99]
It would be useful to be able to differentiate the regular browser from the electron platform.

**Comment by janpio** [comment]
Indeed. Won't be super easy or clean though as Electron seems to just use the `browser` implementation of the plugin. 

Would `platform: 'browser'` be the only thing that has to be changed if Electron?

Is there a way to reliably identify Electron via JS?

**Comment by goffioul** [comment]
I think so, using `navigator.userAgent`, which yields the following (when building with electron platform in debug mode, but I guess it's the same in release mode):
`navigator.userAgent
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) com.lincor.medialinc/4.3.2 Chrome/69.0.3497.106 Electron/4.0.1 Safari/537.36"`

**Comment by janpio** [comment]
That would mean that looking for ` Electron/` in the UA string could be a solution. Could be implemented quite cleanly in https://github.com/apache/cordova-plugin-device/blob/db0ad32f2a84db7cb4dd31887417fff0a59eac2f/src/browser/DeviceProxy.js#L23-L25 Do you want to open a PR?

**Comment by goffioul** [comment]
Don't have time right now to create a full PR, but it's quite trivial to implement:
```
function getPlatform () { 
     return navigator.userAgent.indexOf('Electron') !== -1 ? 'electron' : 'browser';
 }
```

**Comment by janpio** [comment]
https://github.com/apache/cordova-plugin-device/edit/master/src/browser/DeviceProxy.js ;)

**Comment by cldtech** [comment]
`function isElectron() {
  //if electron or android
  if(window.cordova.platformId === 'electron' || device.platform === 'android') {

  }
  //if browser
  else if (device.platform === 'browser' && window.cordova.platformId !== 'electron') {

  }
  else {
    console.log('Unknown platform!');
  }
}`

**Comment by cldtech** [comment]
This works for me as of today.

```
function isElectron() {
  //if electron or android
  if(window.cordova.platformId === 'electron' || device.platform === 'android') {

  }
  //if browser
  else if (device.platform === 'browser' && window.cordova.platformId !== 'electron') {

  }
  else {
    console.log('Unknown platform!');
  }
}
```
